language: ruby
cache: bundle
sudo: false
rvm:
  - 1.9.3
  - 2.3.0
  - jruby
  - jruby-head
  - rbx-2
before_install:
  - gem update --system
  - gem install bundler
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Djruby.compile.mode=OFF -J-Djruby.compile.invokedynamic=false'
gemfile:
  - Gemfile
  - gemfiles/Gemfile.actionpack3.2
  - gemfiles/Gemfile.actionpack4.0
script: bundle exec rake
